# Generated by Django 3.1.7 on 2021-05-01 22:51

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco_pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('nome_rua', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=3)),
                ('nome_cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Telefone para contato', max_length=31)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco_pessoa')),
            ],
        ),
    ]
