# Generated by Django 3.1.7 on 2021-05-02 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210501_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Telefone para contato', max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_employee', models.BooleanField(default=False, verbose_name='Funcionário')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Endereco_pessoa',
            new_name='Endereco',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
