# Generated by Django 3.1.7 on 2021-05-05 00:51

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210502_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='endereco',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_cep',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_estado',
            field=models.CharField(default=0, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_nome_cidade',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_nome_rua',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_numero',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
